language: ruby

rvm:
  - 2.1
  - 2.2.6
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.1

install:
  - "gem install bundler"
  - "bundle install --jobs=3 --retry=3"

env:
  -
  - PAPERCLIP_VERSION=3.4.0
  - PAPERCLIP_VERSION=3.5.0
  - PAPERCLIP_VERSION=4.0.0
  - PAPERCLIP_VERSION=4.1.0
  - PAPERCLIP_VERSION=4.2.0
  - PAPERCLIP_VERSION=4.3.0
  - PAPERCLIP_VERSION=5.0.0

script: "bundle exec rake spec"

branches:
  only:
    - master
